// <auto-generated />
using GenePlanet.HaveIBeenBreached.BreachedEmails.EfCoreEmailAddressCollectionAdapter;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GenePlanet.HaveIBeenBreached.BreachedEmails.EfCoreEmailAddressCollectionAdapter.Migrations
{
    [DbContext(typeof(BreachedEmailsDbContext))]
    [Migration("20210318052417_Initial migration")]
    partial class Initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("GenePlanet.HaveIBeenBreached.BreachedEmails.EfCoreEmailAddressCollectionAdapter.EmailAddressDto", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.HasKey("Address");

                    b.ToTable("EmailAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
