// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace GenePlanet.HaveIBeenBreached.BreachedEmails.EfCoreEmailAddressCollectionAdapter.Migrations
{
    [DbContext(typeof(BreachedEmailsDbContext))]
    internal class BreachedEmailsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity(
                "GenePlanet.HaveIBeenBreached.BreachedEmails.EfCoreEmailAddressCollectionAdapter.EmailAddressDto", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.HasKey("Address");

                    b.ToTable("EmailAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}